[window]
dynamic_title = true
# decorations = "none"
opacity = 0.96
blur = true
dynamic_padding = true

[font]
size = 10.0

[font.offset]
y = -1

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[terminal.shell]
program = "nu"

[keyboard]
bindings = [

    { key = "Space", mods = "Shift|Control", action = "None" },
    { key = "M", mods = "Shift|Control", action = "ToggleViMode" },

    { key = "U", mode = "Vi|~Search", action = "Left" },
    { key = "I", mode = "Vi|~Search", action = "Down" },
    { key = "P", mode = "Vi|~Search", action = "Up" },
    { key = "E", mode = "Vi|~Search", action = "Right" },

    { key = "A", mode = "Vi|~Search", action = "ToggleViMode" },
]

[[hints.enabled]]
regex = '''\w(?:\S*\/\S*)+\w'''
action = "Copy"
binding = { key = "P", mods = "Control|Shift" }

[[hints.enabled]]
regex = '''[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'''
action = "Copy"
binding = { key = "D", mods = "Control|Shift" }

[colors.primary]
background = "#0a0a0a"
