[font]
size = 10.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[shell]
program = "pwsh"

[window]
dynamic_title = true

[keyboard]
bindings = [
  { key = "Space", mods = "Control", action = "None" },

  { key = "U", mode = "Vi|~Search", action = "Left" },
  { key = "I", mode = "Vi|~Search", action = "Down" },
  { key = "P", mode = "Vi|~Search", action = "Up" },
  { key = "E", mode = "Vi|~Search", action = "Right" },

  { key = "A", mode = "Vi|~Search", action = "ToggleViMode" },
]
