theme = "base16_default_dark"

[editor]

line-number = "relative"
default-line-ending = "lf"
shell = ["pwsh", "-c"]
bufferline = "multiple"

[editor.cursor-shape]

insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]

display-messages = true
# display-inlay-hints = true

[editor.indent-guides]

render = true

[editor.file-picker]

hidden = true

[keys.select]

u = "extend_char_left"
i = "extend_line_down"
p = "extend_line_up"
e = "extend_char_right"

[keys.normal]

u = "move_char_left"  # h
i = "move_line_down"  # j
p = "move_line_up"    # k
e = "move_char_right" # l

h = "undo"
H = "redo"
j = "move_next_word_end"
J = "move_next_long_word_end"
l = "insert_mode"
L = "insert_at_line_start"
k = "paste_after"
K = "paste_before"
I = "join_selections_space"

C-s = ":w"
C-q = ":q"
C-g = ":bc"

[keys.normal."é"]

d = "goto_next_diag"
D = "goto_last_diag"
f = "goto_next_function"
t = "goto_next_class"
a = "goto_next_parameter"
c = "goto_next_comment"
T = "goto_next_test"
p = "goto_next_paragraph"
g = "goto_next_change"
G = "goto_last_change"
" " = "add_newline_below"

[keys.normal."ç"]

d = "goto_prev_diag"
D = "goto_first_diag"
f = "goto_prev_function"
t = "goto_prev_class"
a = "goto_prev_parameter"
c = "goto_prev_comment"
T = "goto_prev_test"
p = "goto_prev_paragraph"
g = "goto_prev_change"
G = "goto_first_change"
" " = "add_newline_above"

[keys.insert]
C-space = "completion"
